baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo Theme Primer'

theme = ["hugo-theme-primer"]

enableGitInfo = true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

  [markup.goldmark.renderer]
    unsafe= true # allow html tags in content files

# https://palant.info/2020/06/04/the-easier-way-to-use-lunr-search-with-hugo/
[outputFormats]
  [outputFormats.SearchIndex]
    baseName = 'search'
    mediaType = 'application/json'

[outputs]
  home = ['HTML', 'RSS', 'SearchIndex']
